name: Testing configuration variable

on: 

  workflow_dispatch:

env:
  cloud: google-cloud

jobs:
  Greetings_job:
    runs-on: ubuntu-latest
    env:
      greeting: hello
  
    steps:
    - name: greeting priyanka
      run: echo "$greeting $first_name, Welcome to $cloud and you are using $cloud
        with project id  ${{ vars.Project_id }}!"
      env:
        first_name: priya

