name: Testing workflow variable

on:
  workflow_dispatch

env: 
 cloud: google-cloud

jobs:
  greetingjob:
    runs-on: ubuntu-latest
    env:
      greeting: hello
    steps:
      - name: "Hello priyanka"
        run: echo "$greeting $first_name,welocome to $cloud!"
        env: 
          first_name: priya
